baseurl: /tufte-css-jekyll
title: tufte-css-jekyll
header: true
subtitle: A Jekyll theme based on tufte-css
author: Stephan Druskat
email: mail [at] sdruskat [dot]
description: A Jekyll theme based on tufte-css
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:categories/:year/:month/:day/:title.html
timezone: Europe/Berlin
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'DeployToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: src